/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package cairo-1.16.0 */
#define VERSION_cairo "1.16.0"
#define MIN_VERSION_cairo(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  16 || \
  (major1) == 1 && (major2) == 16 && (minor) <= 0)

/* package pangocairo-1.42.4 */
#define VERSION_pangocairo "1.42.4"
#define MIN_VERSION_pangocairo(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  42 || \
  (major1) == 1 && (major2) == 42 && (minor) <= 4)

/* package pango-1.42.4 */
#define VERSION_pango "1.42.4"
#define MIN_VERSION_pango(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  42 || \
  (major1) == 1 && (major2) == 42 && (minor) <= 4)

