/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package gtkglext-1.0-1.2.0 */
#define VERSION_gtkglext_1_0 "1.2.0"
#define MIN_VERSION_gtkglext_1_0(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)

