/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package libglade-2.0-2.6.4 */
#define VERSION_libglade_2_0 "2.6.4"
#define MIN_VERSION_libglade_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 4)

